### PR TITLE
ONIX techniques: first proposal for Supports nonvisual reading

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
Thanks to Gautier and Chris for this proposal.

This is a first draft, on which we await comments.

There is a discussion among editors whether to include the possibility of there being audio or video content in the publication and then check if there are text alternatives for this content.

### CODE REVIEW

**Review by clapierre — CHANGES_REQUESTED** [review]
I think the variable names 
"non_textual_content_still" and "textual_alternative_still" is not clear.

Should these instead be?
non_textual_content_exists 
and 
textual_alternatives_exist_for_all_non_textual_content

**Comment by gautierchomel** [comment]
> I think the variable names "non_textual_content_still" and "textual_alternative_still" is not clear.
> Should these instead be? non_textual_content_exists and textual_alternatives_exist_for_all_non_textual_content

The first intent was to include every non-textual content in the same check, including video and audio. That was a long list and would probably trigger numerous false positives (for example if there are images and video, the images have alt text but the audio has no caption). This [commit shows the list as per the first intent](https://github.com/w3c/publ-a11y/compare/main...techniques_gc#diff-70838e740c1baf42b7b6b7493b8b611254625d45b694e21ce3d8cbf04d0960aaR187).

This proposal considers only Still Images, maybe the wording can be better. Would non_textual_content_images do?

We are discussing adding additional checks for non_textual_content_motions, _non_textual_content_audio_ and the related _textual_alternative_motions_ and _textual_alternative_audio_

**Comment by GeorgeKerscher** [comment]
I think the order may be wrong. We have in the principals
Supports Visual Adjustments
Supports Non-Visual reading
Conformance is the final section.

I think the previous PR made the change.

**Comment by madeleinerothberg** [comment]
Are we discussing the strings to be displayed or were those decided elsewhere? If we are, I suggest editing for Instruction 3 which is when we don't have metadata stating this is a "real text" book. Since we would expect most ebooks to meet that bar, instead of saying the book "May not be fully readable in read aloud and braille" I suggest we delete the word "fully" and say it may not be readable.

For Instruction 2, where the book is in real text but has images that are not provided with alternative text, the word "fully" makes sense.

**Review by madeleinerothberg — CHANGES_REQUESTED** [review]
See comment about Instruction 3

**Comment by GeorgeKerscher** [comment]
Hi,

Where Madeleine suggests that we say for item3  It is not readable, do we mean not readable in readaloud or braille?

Also in this section, there is one typo. Where it says:
publication necessary to use and understanding, including text, images (via their alternative 

I think understanding should be understand.

**Comment by madeleinerothberg** [comment]
Apologies for my laziness -- yes, I meant to propose to keep the whole sentence except the word "fully" so it would read:
"May not be readable in read aloud and braille"

**Comment by gautierchomel** [comment]
@madeleinerothberg strings are in the [principles document](https://rawcdn.githack.com/w3c/publ-a11y/f7f9921cde19fd819683e9ea420482577f84088f/UX-Guide-Metadata/draft/principles/index.html#example-compact-explanations), we can propose the change there and report here.

Most ebooks with real text and few image may still be "almost fully" readable, few parts may be hard to understand if textual alternative is missing, that's why we opted for the addition of the word "fully". _may not be readable_ is not telling that most of the content is probably readable.

Exemple: a novel with a publisher logo and a photograph of the author missing alt text

**Comment by GeorgeKerscher** [comment]
I believe we are defining the strings in the principles section. We are referencing the compact presentation in the techniques.

Here is what the principles section says right now:
EXAMPLE 4: Compact explanations
• Readable in read aloud and braille.
• May not be fully readable in read aloud and braille.
• Not fully readable in read aloud and braille.

Again, there are subtile  differences in the last two. I am not sure if people will get the differences.

Might we say: • Portions may not be readable in read aloud and braille.
and for the final case: Portions will not be readable in read aloud and braille

**Comment by GeorgeKerscher** [comment]
This section still needs the order fixed to align with the Principles and the Schema section.

Non visual reading should be first.

**Comment by madeleinerothberg** [comment]
> @madeleinerothberg strings are in the [principles document](https://rawcdn.githack.com/w3c/publ-a11y/f7f9921cde19fd819683e9ea420482577f84088f/UX-Guide-Metadata/draft/principles/index.html#example-compact-explanations), we can propose the change there and report here.

OK, I'll try to figure out how to open an issues there, if after reading this comment others agree that it is needed. I may be wrong.
 
> Most ebooks with real text and few image may still be "almost fully" readable, few parts may be hard to understand if textual alternative is missing, that's why we opted for the addition of the word "fully". _may not be readable_ is not telling that most of the content is probably readable.
> 
> Exemple: a novel with a publisher logo and a photograph of the author missing alt text

I agree -- but wouldn't these books will fall under Instruction 2 -- real_text AND non_textual_content_still AND NOT textual_alternative_still.

I am discussing the ones that fail instruction 2 and fall through to instruction 3. Books with no real_text are not "maybe not fully readable" but instead "may not be readable at all" because they have no assertion of real text.

**Comment by avneeshsingh** [comment]
If we are OK with the technique, and the improvements are confined to text in principles, then we should merge this pull request and update it again when we finalize the text for principles.

**Pull request merged**
