### PR TITLE
exact string matching

### PR DESCRIPTION
**Pull request by clapierre**
now making sure the exact strings for conformance are checked

### CODE REVIEW

**Comment by clapierre** [comment]
This addresses the following conformance matching string issue brought up by @wareid in issue
#471 Editorial Feedback for the ONIX/EPUB Techniques Document

**Comment by GeorgeKerscher** [comment]
It looks good to me, but I would like to have others review.

**Review by GeorgeKerscher — APPROVED** [review]

**Review by gregoriopellegrino — APPROVED** [review]

**Comment by mattgarrish** [comment]
Do we really need to set all these variables? From what I can tell, only the conformance string to display and the wcag level matter in terms of setting statements in the following section.

For example, all of the 1.1 matching strings could be reduced to something like:

<span><b>IF</b> the result of calling <a href="#check-for-node">check for node</a> on <var>package_document</var>, <code class="xpath">/package/metadata/meta[@property="dcterms:<i>conformsTo</i>" and matches(normalize-space(.), 'EPUB Accessibility 1\.1 - WCAG 2\.[0-2] Level [A]+')</code> :</span>
                       <span>
                            <b>THEN</b> <b>LET</b> <var>conformance_str</var> = replace(normalize-space(.), ' - ', ''), 
                            and <b>LET</b> <var>wcag_level</var> = replace(normalize-space(.), 'EPUB Accessibility 1\.1 - WCAG 2.[0-2] Level ', '').

(I don't know if we'd really want to use xslt syntax for setting the variables, but it's just to give an idea that you can process the existing string to get the same value you generate below.)

In any case, if conformance_str is not an empty string, then you'd know you can continue to display conformance information. You'd still use the wcag_level to give the generic statement and conformance_str would contain the specific information rather than having to rebuild almost exactly the same string you just decomposed.

The conformance statement would presumably still be translatable; it would just require an extra step to match the English string that results after removing the dash into whatever the equivalent translation would be (i.e., you wouldn't show every possibility in the techniques document, but maybe note that the value could translate to one of 9 possible permutations of 1.1 identifiers).

**Comment by clapierre** [comment]
@gregoriopellegrino what do you think about @mattgarrish suggestion?
I don't know how I would write it up since the only variable set is the WCAG level and how it would work in the Instructions portion without the other variables being set. I am sure there is a more elegant way to do this but I haven't the time to figure that out.

**Comment by mattgarrish** [comment]
I can open a new PR based on this one to give a better idea of how it might work. I assume this processing is based on the onix metadata, but in that case the information comes decomposed and has to be built up. For the conformsTo string, it seems like a lot of unnecessary work to break it all apart just to put it back together.

**Pull request merged**
