### PR TITLE
Metadata processor

### PR DESCRIPTION
**Pull request by mattgarrish**
I've implemented the logic from the epub techniques document into a javascript processor. It will output a `dl` with each category and its statements.

I've tried not to optimize the code but write it out to match the statements in the techniques as exactly as I can to make it as easy as possible to pinpoint where issues are.

After merging, you should be able to test this at https://w3c.github.io/publ-a11y/a11y-meta-display-guide/experiments/meta-processor/

<strike>I'll look at adding ONIX support to it next.</strike>

Now also supports ONIX record processing

### CODE REVIEW

**Comment by mattgarrish** [comment]
Forgot to mention, but there's nothing special about the processor. If you check out the branch you should just be able to launch the html page and try it out.

**Comment by gautierchomel** [comment]
I locally experimented with our [accessbility metadata test epub](https://github.com/edrlab/thorium-reader-epub-tests/blob/main/Rare_EPUB_test_suit/a11y_metadata/package.opf ) and got as result:

> Result of Processing:
> Visual adjustments
> Appearance can be modified
> Supports nonvisual reading
> Readable in read aloud or dynamic braille
> Conformance

**Review by gautierchomel — APPROVED** [review]

**Comment by gautierchomel** [comment]
That's a wonderful tool, very easy to use :)
We have to check why the [accessibility metadata test epub](https://github.com/edrlab/thorium-reader-epub-tests/blob/main/Rare_EPUB_test_suit/a11y_metadata/package.opf) does not trigger more fields.

**Comment by mattgarrish** [comment]
Thanks for linking to that file!

When I was testing, I was using one of the IDPF samples and hacking in metadata as I went, but I didn't catch everything.

Turns out I had a "matches" function call in the javascript instead of the proper "match". I fixed it in the last commit so it should generate a complete set of metadata now.

**Comment by gautierchomel** [comment]
Nice, here is the updated output. 


<dl id="result">
    <dt>Visual adjustments</dt>
    <dd>Appearance can be modified</dd>
    <dt>Supports nonvisual reading</dt>
    <dd>Readable in read aloud or dynamic braille</dd>
    <dt>Conformance</dt>
    <dd>
        <p></p>
        <p>This publication is certified by EDRLab</p>
        <p>The certifier's credential is Certifier credential</p>
    </dd>
    <dt>Detailed Conformance Information</dt>
    <dd>
        <p>This publication claims to meet EPUB Accessibility 1.1 WCAG 2.1 Level AA</p>
        <p>The publication was certified by EDRLab with a credential of Certifier credential</p>
    </dd>
    <dt>Pre-recorded audio</dt>
    <dd>Audio only</dd>
    <dt>Navigation</dt>
    <dd>Navigation by table of contents, index, supports page navigation, and headings</dd>
    <dt>Charts, diagrams, math, and formulas</dt>
    <dd>Accessible chemistry contentAccessible math content</dd>
    <dt>Hazards</dt>
    <dd>No hazards</dd>
    <dt>Accessibility summary</dt>
    <dd lang="fr">This is the accessibility summary. This EPUB is for testing purposes, accessibility metadata presented
        are not true but only present to check how they would display into the reading system.</dd>
    <dt>Legal considerations</dt>
    <dd>No legal considerations</dd>
    <dt>Additional accessibility information</dt>
</dl>

**Comment by gautierchomel** [comment]
That's a very nice highlight that the title structure is heavily doubling the list, and with a demo epub heavily loaded in metadatas :)

**Comment by mattgarrish** [comment]
I made one last tweak to separate the statements in the charts section, although from Gregorio's comments to my issues it sounds like this is going to be rewritten soon.

**Comment by mattgarrish** [comment]
I've merged onix processing into this branch so the generator will now accept either a package document or onix record. I've used a rudimentary regex check on the input to see if there is a `<package` or `<ONIXMessage` tag present and send the input to the corresponding processor.

I haven't tested the onix processing extensively. I found the record in the 1.0 techniques and was able to run that through without error, but there may be bugs.

**Comment by mattgarrish** [comment]
I'm going to merge this and add a link to the main page. Will update it as issues get resolved.

**Comment by mattgarrish** [comment]
For the record, the processor is live here: https://w3c.github.io/publ-a11y/a11y-meta-display-guide/2.0/experiments/meta-processor/

I moved the experiments folder under /2.0 so if there are future revisions they can have their own experiments space.

I've updated the [2.0 readme](https://github.com/w3c/publ-a11y/tree/main/a11y-meta-display-guide/2.0) to add a link to it, and also added a link to that 2.0 page to the main readme (the "project page" link in the documents section).

**Comment by clapierre** [comment]
This is awesome, well done Matt.

**Pull request merged**
