### PR TITLE
Small fixes for localization

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
I made small changes to all three files (principles and techniques) to align small discrepancies between strings.

### CODE REVIEW

**Review by gautierchomel — APPROVED** [review]

**Review by GeorgeKerscher — APPROVED** [review]

**Review by clapierre — APPROVED** [review]

**Comment by GeorgeKerscher** [comment]
Has conflicts, cannot merge.

**Comment by gregoriopellegrino** [comment]
I look at them, I fix them

**Comment by clapierre** [comment]
Gregorio, I don't this you merged your changes in, the branch was still in conflict.  I made I assume the same edits as you accepting the branches changes for the extra period inside the <code> block. and then merged them.  Now the branch no longer has conflicts.

**Comment by clapierre** [comment]
@GeorgeKerscher 
when I fixed the conflicts I didn't notice that one had "math" included along with an extra period inside the <code> block and one which didn't.
Do we want the "math" included here?

The accessibility of formulas, charts, math, and diagrams is not available

or

The accessibility of formulas, charts, and diagrams is not available

Currently "math" is NOT included.

**Pull request merged**
