### PR TITLE
Editorial edits

### PR DESCRIPTION
**Pull request by clapierre**
From email Charles sent to editors on 11/30.

### CODE REVIEW

**Comment by gregoriopellegrino** [comment]
It seems to me that for the issue of when to hide hazards we had suggested opening an issue to discuss it, otherwise okay.

**Comment by avneeshsingh** [comment]
Looks good Charles. You can remove the changes in the hazards and open an issue for discussion. We should merge other changes.

**Comment by clapierre** [comment]
Ok Hazards section reverted. Ready to be reviewed / merged

**Comment by clapierre** [comment]
new Hazards Issue #222 added

**Pull request merged**
