### PR TITLE
Update User Experience Guidelines title to 1.1

### PR DESCRIPTION
**Pull request by rickj**
Update User Experience Guidelines title to 1.1

### CODE REVIEW

**Comment by gregoriopellegrino** [comment]
Hi, I think a cross editor discussion is needed. In my opinion this revision of the guidelines is not backward-compatible with the previous one (the logic behind it has changed) so for me it would be an update of a major version (e.g. 2.x).

**Comment by GeorgeKerscher** [comment]
I agree that this is a major revision. The Accessibility Summary alone is enough for the change, but also the language used to describe the various entries has also changed.

**Comment by rickj** [comment]
The intent of my pull request was to get it off of 1.0 as it is causing confusion with internal and publisher contacts when I try to discuss the work that is going on

**Comment by gregoriopellegrino** [comment]
Closing, because we're updating to versione 2.0

**Pull request closed without merging**
