### PR TITLE
Abstract proposal

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
I wrote this abstract taking some texts of mine and of Charles, do you think it could be good?

It is a starting point, we can modify everything.

### CODE REVIEW

**Review by clapierre — APPROVED** [review]
:) looks familiar ;)

**Comment by GeorgeKerscher** [comment]
I think the abstract looks fine. I envision other marketing materials will provide modivation to readers. This is short and to the point. We do not want to go into more debth here.
I approve.

**Review by clapierre — CHANGES_REQUESTED** [review]
From email thread, suggested improvements.

Finding, buying, and finally reading a book is a very personal experience.  For most of us this is routine where we go to a bookstore search for the title we are interested in or perhaps browse the best sellers list, then purchase and start reading the book.

Now consider you are blind and rely on assistive technology to read this book.  Will my screen reader work with this title? Are there image descriptions that will be spoken to describe these images, are there page numbers which are accessible, is the reading order correct so I don't hear chapter 4 before chapter 3?  These are just a few of the accessibility concerns consumers have when trying to purchase and ultimately read electronic publication.

The good news is more and more publishers are creating Born Accessible publications and getting their workflows certified as accessible by trusted organizations.

This document proposes a shared framework for presenting publication accessibility metadata in a user-friendly manner.

**Comment by avneeshsingh** [comment]
"The good news is more and more publishers are creating Born Accessible publications and getting their workflows certified as accessible by trusted organizations."

It looks very specific. Better to say:
The good news is more and more publishers are creating Born Accessible publications and also getting the accessibility validation or audit done by independent organizations.

**Review by gregoriopellegrino — COMMENTED** [review]
updated! please review it

**Review by clapierre — APPROVED** [review]
Looks good, all changed incorporated.

**Pull request merged**
