### PR TITLE
First proposal for Legal considerations in ONIX technique

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
Based on what was defined in the principles, I created a section for Legal considerations with a placeholder where we can then insert the sentence on which we will find consensus.

### CODE REVIEW

**Comment by gregoriopellegrino** [comment]
cc @chrisONIX

**Comment by chrisONIX** [comment]
This looks good and the place holder makes sense while waiting agreement

**Comment by GeorgeKerscher** [comment]
Agreed, looks good while waiting for feedback.

**Review by clapierre — APPROVED** [review]

**Comment by gautierchomel** [comment]
In my understanding we agreed to display only one general sentence for any exemption, so there should be only one check and one sentence "TBD".

**Comment by gautierchomel** [comment]
Now seeing the _update_ commit that regroups all checks into one sentence. 
Not sure about the use of discriminated checks but looks like the final is conforms to the consensus.

**Review by gautierchomel — APPROVED** [review]

**Pull request merged**
