### PR TITLE
Formatting tables

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
I've formatted the tables with CSS and removed "accessibilityFeature" on each row of the second table. It seems much more intelligible to me now.

### CODE REVIEW

**Review by clapierre — COMMENTED** [review]
Everything looks great Gregorio except the feature is just "index" not "linked index" right?
all others listed are the real accessibilityFeature values so I think we must keep it consistent.  Now we can specify linked index maybe in another column.  not sure how to handle that.

**Comment by GeorgeKerscher** [comment]
An index being present is a feature, and if it has links to the top of the page or to a specific spot on the page is worth adding to the summary. Yes, be consistent that all names would have exact correliations to other features.

**Comment by gregoriopellegrino** [comment]
I've changed _Linked index_ to _index_

**Review by clapierre — APPROVED** [review]
Looks good!

**Pull request merged**
