### PR TITLE
Added names to the acknowledgements section

### PR DESCRIPTION
**Pull request by GeorgeKerscher**
I  am just asking Charles to review and go ahead and merge if OK. This is simple and does not need everybody to look at it. I will email the list to the mailing list to see if people want to be added or removed. I commented out the reviewers section.

### CODE REVIEW

**Comment by clapierre** [comment]
George it's hard for me to review this because it seems every section was adjusted. so, I don't just see a commented-out section unfortunately.

**Comment by mattgarrish** [comment]
It appears the document was reformatted to change the indenting and line lengths.

Try reviewing it with the [W3C diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://cdn.statically.io/gh/w3c/publ-a11y/acknowledge/UX-Guide-Metadata/draft/principles/index.html). It ignores the whitespace changes.

**Comment by GeorgeKerscher** [comment]
Did I screw something up? I open it in chrome and see a respect warning.
 
The commented out section seems OK.
 
Perhaps VS Code did some auto formatting?
 
It was not a lot of work to just throw it away.
 
Best
George

**Review by clapierre — APPROVED** [review]
Seems your editor George changed the whitespace, once Matt gave me the diff view it was easy to see and looks great!
Feel free to merge.

**Comment by GeorgeKerscher** [comment]
I removed out the commented section in my copy and still got the respec warning.

**Comment by mattgarrish** [comment]
The warning is unrelated to this change. There's a link to "Example Book Features" in section 4.5.2 but the destination no longer exists. It appears to be an acknowledgement of icon use. I think section can just be deleted.

**Pull request merged**
