### PR TITLE
Ready to merge Localization updates

### PR DESCRIPTION
**Pull request by gautierchomel**
This includes: 

- updated Keys in the canonical.json file for localization
- additional IDs to principles examples so they are identifiable horizontally (same ID in Principle, Technics and JSON)

Raised some issues on the walkway: 

- #392 
- #391 
- #390 
- #371 (solved by aligning Principles to hasard keys)
- #369 
- #368 
- #367

### CODE REVIEW

**Comment by gautierchomel** [comment]
I suggest we merge so the principles get the IDs and make any further improvements to the JSON later.

**Review by clapierre — APPROVED** [review]
Nice work.

**Comment by gautierchomel** [comment]
I implemented one upper level to group keys. 

"detailed-Conformance" remains the only object that has an additional layer, that's due to the structure of the Conformance section.

**Comment by GeorgeKerscher** [comment]
In the principles document on lines 500 and 527, the span should be closed after the</a>.

**Comment by gautierchomel** [comment]
> In the principles document on lines 500 and 527, the span should be closed after the.

Done for those two and three more occurrences. 

That means the "." must be in the JSON value, am I right?

**Pull request merged**
