### PR TITLE
ONIX Rich content refactor - first draft

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
In working on this PR, I realized a few things:

- @chrisONIX: can you help me figure out what ONIX code use to express "Videos have closed captions", "Videos have open captions", "Prerecorded audio has transcript"
- @GeorgeKerscher what does it mean "Prerecorded audio is present"? Maybe it should be in the "Pre-recorded audio" section?
- ONIX doesn't have code to express "Chemical formulas in LaTex," i seems like an edge case that maybe we don't need
- @GeorgeKerscher I changed all the IDs from "charts-diagrams-and-formulas" to "rich-content"

### CODE REVIEW

**Comment by chrisONIX** [comment]
Videos have closed captions
In ONIX - <ProductFormDetail> will include code V210 from code list 175 - https://ns.editeur.org/onix/en/175/V210 to confirm any included video content with sound has closed options 
plus <PrimaryContentType>  or <ProductContentType> will contain one of these values from list 81 - to confirm what type of video content https://ns.editeur.org/onix/en/81 - codes 06, 25, 26, 27, 28, 29, or 30

**Comment by chrisONIX** [comment]
Videos have open captions:
In ONIX - ProductFormDetail will include code V211 from code list 175 - https://ns.editeur.org/onix/en/175/V211 to confirm any included video content with sound has open captions
plus PrimaryContentType or ProductContentType will contain one of these values from list 81 - to confirm what type of video content https://ns.editeur.org/onix/en/81 - codes 06, 25, 26, 27, 28, 29, or 30

**Comment by chrisONIX** [comment]
Prerecorded audio has transcript
In ONIX - ProductFormDetail will include V212 from code list 175 https://ns.editeur.org/onix/en/175/V212 to confirm there is a transcript available of all the prerecorded audio. 
(ONIX also allows someone to send a link to download the transcript but I don't think that needs to be included here).
List 81 and PrimaryContentType or ProductContentType will use one of the video with sound values as in the caption examples, or for an audio only product it will be one of 01, 02, 13, 21 or 22

**Review by clapierre — APPROVED** [review]

**Comment by gregoriopellegrino** [comment]
I've added closed captions, open captions and transcript. For me we can merge (I'll resolve the conflict before merging).

**Review by clapierre — APPROVED** [review]
new changes look good Gregorio.

**Pull request merged**
